services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - /Users/sumeet/Public/db-volumes/mongodb:/data/db
      - /Users/sumeet/git_repos/servers/mongodb/mongodb-keyfile:/data/mongodb-keyfile
      - /Users/sumeet/git_repos/servers/mongodb/init:/docker-entrypoint-initdb.d
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile"]
    restart: always